# don't import too much here to allow the command-line part to run quickly.
# once the command-line part is successful then we can pull everything in
# and run the script proper

import argparse

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        prog="main.py",
        description="",
    )

    parser.add_argument("stats_xml", help="Path to Stats.xml.")
    parser.add_argument("song_listing_csv", help="Path to file generated by getavailablesongs.py")
    parser.add_argument("--template", default="template.xlsx", help="Path to template .xlsx file")
    parser.add_argument("--output", default="output.xlsx", help="Output path")

    args = parser.parse_args()

    # arguments good, now import everything and run the main script

    from pathlib import Path

    from openpyxl import load_workbook
    from openpyxl.worksheet.worksheet import Worksheet

    import analysis
    from table_stats import TableStats

    s = TableStats()
    s.fill_stats_xml(Path(args.stats_xml))
    s.fill_song_listing(Path(args.song_listing_csv))

    wb = load_workbook(args.template)

    def fetch(sheet_name: str) -> Worksheet:  # noqa: D103
        print(f"Generating {sheet_name} sheet...")
        return wb[sheet_name]

    ws = fetch("General")
    analysis.create_general_sheet(ws, s)

    ws = fetch("Most Played Charts")
    analysis.create_most_played_charts_sheet(ws, s)

    ws = fetch("Most Played Songs")
    analysis.create_most_played_songs_sheet(ws, s)

    ws = fetch("Most Played Packs")
    analysis.create_most_played_packs_sheet(ws, s)

    ws = fetch("Recently Played Packs")
    analysis.create_recently_played_packs_sheet(ws, s)

    ws = fetch("Pack Completion")
    analysis.create_pack_completion_sheet(ws, s)

    ws = fetch("Highest Scores + Passes")
    analysis.create_highest_scores_sheet(ws, s)

    wb.save(args.output)
